### ISSUE TITLE
PROMO S/P 113 - 122 unable to correspond card image

### ISSUE THREAD

**Issue by CrystMiku** [duanxr/PTCG-CHS-Datasets#7]
hello，我发现数据2个问题：
- 剑盾特典卡中编号113-122的卡图无法对应
- 城市赛 精灵球特典卡、S/P-004的卡图存在较大失真
  - ![image](https://github.com/duanxr/PTCG-CHS-Datasets/assets/150767126/3f934fcf-d2dc-4322-9fad-2d35d44097ca)
  - ![image](https://github.com/duanxr/PTCG-CHS-Datasets/assets/150767126/0e15b87a-3521-4ab3-8ff8-204dde50a7ad)

希望能够得到修复

**Comment by duanxr** [comment]
The issue has been identified and we're working to resolve it ASAP

**Comment by duanxr** [comment]
Fixed it, thanks for your feedback.
